# Generated by Django 5.1.7 on 2025-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_availability_menu_profile_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='basket',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='availability',
            name='ananas',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='bazilik',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='cheese',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='ham',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='salyami',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='species',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tomato_sauce',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ananas',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='bazilik',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cheese',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ham',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='salyami',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='species',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tomato_sauce',
            field=models.BooleanField(default=None),
        ),
    ]
