# Generated by Django 5.2 on 2025-04-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_menu_description_menu_price_profile_basket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pepperoni', models.IntegerField(default=0)),
                ('margaret', models.IntegerField(default=0)),
                ('hawaiian', models.IntegerField(default=0)),
                ('Four_cheeses', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='basket',
        ),
    ]
