# Generated by Django 5.2 on 2025-04-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orders_delete_images_remove_profile_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
