# Generated by Django 5.2 on 2025-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_orders_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.TextField(default='')),
                ('dish1', models.IntegerField(default=0)),
                ('dish2', models.IntegerField(default=0)),
                ('dish3', models.IntegerField(default=0)),
                ('dish4', models.IntegerField(default=0)),
                ('dish5', models.IntegerField(default=0)),
                ('dish6', models.IntegerField(default=0)),
            ],
        ),
    ]
