# Generated by Django 5.2 on 2025-04-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
